apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-arm
  namespace: default
  labels:
    app: mediawiki-arm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediawiki-arm
  template:
    metadata:
      labels:
        app: mediawiki-arm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - arm64
      containers:
      - name: mediawiki-arm
        image: <Private-Docker-Registry-path>/mediawiki:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-arm
spec:
  type: NodePort
  selector:
    app: mediawiki-arm
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "mediawiki-arm-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: mediawiki-arm
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "mediawiki-arm"
              servicePort: 80
